version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  
      LOG_CHANNEL: $LOG_CHANNEL
      OWNER_ID: $OWNER_ID
      BOT_TOKEN: $BOT_TOKEN
